spring.application.name=demo

# spring.datasource.url=jdbc:postgresql://localhost:5432/user
# spring.datasource.password=2707
# spring.datasource.username=postgres

spring.datasource.url=${JDBC_URL}
spring.datasource.password=${JDBC_PASS}
spring.datasource.username=${JDBC_NAME}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${email}
spring.mail.password=${pass}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true   
spring.mail.properties.mail.smtp.starttls.required=true

spring.key=mySecertKey
spring.jwt=hagsdyugaduvusuagut8qteydvsvufsatcxy12i01u29ybxqitwuqivwdcuqtwuggsyacusfyuqto1oncbqcg9y9q2 