name: Keep Render Awake

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Server
        run: curl https://project-x-qa4a.onrender.com