name: Keep Render Awake

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Wake Render
        run: |
          echo "Pinging Render..."
          curl --retry 1 --retry-delay 1 \
          https://project-x-1-2yzg.onrender.com/public/api/v1/ping